apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workloadname }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.workloadname }}
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: {{ .Values.workloadname }}
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: {{ .Values.workloadname }}
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: {{ .Values.workloadname }}
    conventions.carto.run/framework: spring-boot
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.actuator.port: "8080"
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: {{ .Values.workloadname }}
  ports:
  - targetPort: 8080
    port: 8080
    name: http
